### PR TITLE
Stringable: method call VS cast

### PR DESCRIPTION
**Pull request by HeahDude**

### CODE REVIEW

**Comment by lyrixx** [comment]
Thanks

**Comment by mykiwi** [comment]
just for notice on my machine, `benchToStringMethod` is usually faster

**Comment by HeahDude** [comment]
@mykiwi thanks for the feedback :). What PHP version have you used?
I've run the test a lot of times and the cast was always faster even 1x to 1.75x at some point, but every times with PHP 7.4.

**Comment by mykiwi** [comment]
7.4 too, here are some examples:
[asciicast](https://asciinema.org/a/321613)

**Pull request merged**
